#!/usr/bin/env bash
set -euo pipefail

if [[ "$EUID" == "0" ]];then
	echo "Do not run this as root !"
	echo "Paru requires unprivileged user"
	exit 1
fi

# Update packages
sudo pacman -Syu --noconfirm

# Install git, base-devel, and curl (needed for building AUR packages)
sudo pacman -S --needed --noconfirm base-devel git curl

if ! command -v paru &> /dev/null; then
	# Clone the paru repository from the AUR
	git clone "https://aur.archlinux.org/paru.git" "paru"

	# Change into the cloned directory
	cd "paru" || exit 1

	# Build and install paru
	makepkg -si --noconfirm

	# Return back
	cd ..
fi

# Remove paru installation dir
[[ -d "paru" ]] && rm -rf "paru"

# Clone my Arch Sync tool
git clone "https://github.com/TomBos/Arch-Package-Sync.git" "APKGS"

# Change into the cloned directory
cd "APKGS" || exit 1

# Install APKGS
USE_PARU=1 USE_FLATPAK=1 bash "installer"

# Return back
cd ..

# Remove installation dir
[[ -d "APKGS" ]] && rm -rf "APKGS"

# Remove every bash file made by system
for f in \
	"$HOME/.bash_history" \
	"$HOME/.bash_logout" \
	"$HOME/.bash_profile" \
	"$HOME/.bashrc" \
	"$HOME/.bash_login"
do
  [[ -f "$f" ]] && rm -f "$f"
done

# Prepare dotfiles repo
if [[ ! -d "$HOME/.dotfiles" ]];then
	git clone "https://github.com/TomBos/.dotfiles" ".dotfiles"
fi

# Change into cloned directory
cd ".dotfiles" || exit 1

# Download stow if missing
if ! command -v stow &> /dev/null; then
	sudo pacman -S stow
fi

# Remove entires used by dotfiles
rm -f "$HOME/.local/state/apkgs/{paru,pacman,flatpak}"

# Symlink dotfiles
stow --no-folding --target="$HOME" .

# Prompt for reboot
echo "Setup finished please reboot your machine !"

