#!/usr/bin/env bash
set -euo pipefail

# Update packages
sudo pacman -Syu --noconfirm

# Install git, base-devel, and curl (needed for building AUR packages)
sudo pacman -S --needed --noconfirm base-devel git curl

# Clone the paru repository from the AUR
git clone "https://aur.archlinux.org/paru.git" "paru"

# Change into the cloned directory
cd "paru" || exit 1

# Build and install paru
makepkg -si --noconfirm

# Return back
cd ..

# Remove paru installation dir
[[ -d "paru" ]] && rm -rf "paru"

# Clone my Arch Sync tool
git clone "git@github.com:TomBos/Arch-Package-Sync.git" "APKGS"

# Change into the cloned directory
cd "APKGS" || exit 1

# Enable paru and flatpak in my installer
sed -i 's/^# \(USE_PARU=.*\)/\1/' installer
sed -i 's/^# \(USE_FLATPAK=.*\)/\1/' installer

# Install APKGS
bash "installer"

# Return back
cd ..

# Remove installation dir
[[ -d "APKGS" ]] && rm -rf "APKGS"

# Remove every bash file made by system
for f in "$HOME"/.bash*; do
  [[ -f "$f" ]] && rm -f "$f"
done

# Prepare dotfiles repo
git clone "https://github.com/TomBos/.dotfiles" ".dotfiles"

# Change into cloned directory
cd ".dotfiles" || exit 1

# Symlink dotfiles
stow --no-folding --target="$HOME" .

# Prompt for reboot
echo "Setup finished please reboot your machine !"

